name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: sudo snap install ipfs jq
      - run: ipfs init --profile server
      - run: ipfs daemon &
      - name: wait for ipfs daemon
        run: wget -q --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 60 http://127.0.0.1:5001/api/v0/version
      - run: make publish
      # todo: add $(cat versions) to cluster (and wait)
      # todo: update dist dnslink if changed.
  
  lint: 
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm ci --no-audit --progress=false
      - run: npm run lint
