name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: sudo snap install ipfs jq
      - run: ipfs daemon --init
      - run: make publish
      # todo: add $(cat versions) to cluster (and wait)
      # todo: update dist dnslink if changed.
  
  lint: 
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm ci --no-audit --progress=false
      - run: npm run lint
